openapi: 3.0.0
info:
  title: Shoppa
  description: Shoppa Online Shopping API
  version: 1.0.0
paths:
  /users:
    get:
      description: Get all users
      operationId: getUsers
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      description: Get user by id
      operationId: getUserById
      parameters:
       - name: id
         in: path
         required: true
         schema:
            type: integer
      responses:
         200:
           description: Success Response
           content:
              application/json:
               schema:
                $ref: '#/components/schemas/User'

components:
   schemas:
     User:
      type: object
      properties:
        _id:
          type: string
          example: "632d2713151c158dd8845e5b"
        email:
          type: string
          example: "john.carter@gmail.com"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Carter"
        contactNumber:
          type: string
          example: "07781882882"
      
  